Traceback (most recent call last):
  File "e:\Study\AutomateCourse\Debugging\exception.py", line 33, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
